### ISSUE TITLE
Decorated class methods can't be tracked due to type obfuscation

### ISSUE THREAD

**Issue by mehdibenamorr** [padre-lab-eu/pypads#6]
An example of the issue is in BaseSearchCV of Scikit-learn where some bound methods are decorated with @if_delegate_has_method. This led to the confusion where PyPads can't decide on the function type thus getting the corresponding wrapper.

**Comment by Weissger** [comment]
We found a workaround for @if_delegate_has_method. The workaround works for every function being extended by a class / __get__ function. Other special cases might need unique solutions.
